"""add likes

Revision ID: ed725c1edd5a
Revises: 1b53c82efc92
Create Date: 2023-01-11 23:51:05.691502

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ed725c1edd5a'
down_revision = '1b53c82efc92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
